First Code Review
dev1980/BUILDING-WITH-RESPONSIVE-DESIGN pull request #1
Opened 2019-08-08 21:36 UTC by David405

2019-08-09 01:47 UTC, Ispirett commented
# Reviewing

2019-08-09 02:08 UTC, Ispirett requested changes
Hey, @David405  @dev1980  really great job so so far :1st_place_medal: You guys did a great  job with the layout. There are just a few  things to take care of  :+1:  

- [ ] The responsiveness of the site needs some adjusting.
### Breakpoints.
small: max-width around 700
medium: max-width around 1000
large: max-width over 1000

**you have implemented two of them** 
You are using `min-width` which is not an issue if you use it properly. 
But the main issue is the site is not fully responsive. 
For example: on line `1012` in your CSS file , you have only setup  adjustments for `nav-search` and `time`
 
**I encourage you to watch the original site and try to mimic the changes you see when you resize the browser.  You can always refer to information from the Odin project on responsive design.**

- [ ] HTML errors
Also,  guys, There are a lot of HTML errors on this page use this tool and please correct them https://validator.w3.org/


**Also, remember You should use Github/Git Flow in this project. However, changing it now would take too much time.
Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.**

2019-08-13 00:28 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-13 00:37 UTC, Torres-ssf commented
### Nice work team :clap: 
Your project looks really nice and you should be proud of it.

But there is still one thing that we need to change. I notice that the stickler is not verifying your project. Maybe this is happening because it's not set up properly. Please check the instruction on the pathwrite on how to set up the linter and make it work on this project. You will also need to fix errors(if the linter found any). I know that in the past we didn't pay much attention to it but linting is important to reduce errors and improve the overall quality of your code. Using the linter also gives a professional look in your repository. Please kindly make this change and submit for code review again.

[FOR FUTURE PROJECT]
 You should use Github/Git Flow in future projects. It's really easy to use it and will make your repository looks more professional. You will find instructions in the Patwright lesson description.

2019-08-13 00:47 UTC, Torres-ssf requested changes
### Nice work team :clap: 
Your project looks really nice and you should be proud of it.

But there is still one thing that we need to change. I notice that the stickler is not verifying your project. Maybe this is happening because it's not set up properly. Please check the instruction on the pathwrite on how to set up the linter and make it work on this project. You will also need to fix errors(if the linter found any). I know that in the past we didn't pay much attention to it but linting is important to reduce errors and improve the overall quality of your code. Using the linter also gives a professional look in your repository. Please kindly make this change and submit for code review again.

[FOR FUTURE PROJECT]
 You should use Github/Git Flow in the future

2019-08-14 03:31 UTC, Ispirett requested changes
Hey @dev1980 @David405 I can see the stickler problem still exists. 

You can try use this in your stickler file instead  :+1: https://github.com/Ispirett/newsweek/blob/master/stickler.yml

2019-08-15 07:44 UTC, bolah2009 requested changes
## Nice Job Team

You almost there :smile: 

Since the main objective of the project is to make a **responsive** clone of [this page](https://thenextweb.com/) I would suggest making sure [this section]() (shown below) is responsive and have the small fixed navbar on smaller screens.

| Clone | Source Page |
| :-----: | :-----: |
| ![tnw clone reponsive](https://user-images.githubusercontent.com/36057474/63080258-86135b00-bf38-11e9-9338-01c61b60f9bb.png)  | ![tnw source reponsive](https://user-images.githubusercontent.com/36057474/63080276-8d3a6900-bf38-11e9-8395-c76739a25817.png)  |

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-15 20:20 UTC, Oghenebrume50 commented
Reviewing......

2019-08-15 21:22 UTC, Oghenebrume50 requested changes
Hi guys good job so far kudos on your progress, I still have to stress on the responsiveness, it is still not responsive, please compare with the original site display at each breakpoint to know what to do. 
![111](https://user-images.githubusercontent.com/37092867/63127553-92d09700-bfaa-11e9-8561-f9f0aed69605.png)
![11](https://user-images.githubusercontent.com/37092867/63127554-92d09700-bfaa-11e9-8380-9aaa543e626d.png)
From the screenshot above you can see it is not displayed properly. And avoid leaving spaces around containers where it is not needed. 

Please fix that and submit for re-review

2019-08-17 03:02 UTC, bolah2009 approved these changes
## Good Progress. :tada: 

The [clone](https://raw.githack.com/dev1980/BUILDING-WITH-RESPONSIVE-DESIGN/development/index.html) looks good to me now and responsive. :+1: 

### It's a :+1: from me.

### Although you can merge now, I strongly recommend you check the comments below and add the appropriate `linter files`.

- [Next Project] Use GitHub Flow: For HTML & CSS projects, use only one feature branch (e.g. `embedding-images-and-video`, `html-forms`, `responsive-design`, etc) and **do not merge any feature branch to master until it's been approved**.


Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### Note that comments tagged `OPTIONAL` are strongly recommended but not required to approve the project.

2019-08-17 03:02 UTC, bolah2009 commented on css/.stickler.yml
> +    config: 'stylelint.config.js'
`HINT`

Use `.stickler.yml` file in the root path of the project.

2019-08-17 03:02 UTC, bolah2009 commented on eslint.config
> +}
`HINT`

This config file is not relevant to this project. Please, delete. :+1:

2019-08-17 03:02 UTC, bolah2009 commented on .stickler.yml
> +    - "webroot/bower_components/*"
`HINT`

Yes, this is the right location for this file. :smile: But with the wrong content. :worried: 

Let's use [this file](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml) instead.

``` yml
linters:
  stylelint:
    config: 'stylelint.config.js'
```
- Also, add the `stylelint.config.js` that was referenced above, this can be found [here](https://github.com/microverseinc/linters-config/blob/master/css/stylelint.config.js)

If you are having an issue with setting up linter, read the `Troubleshooting` section of [this repo](https://github.com/microverseinc/linters-config/tree/master/css).

2019-08-17 11:49 UTC, dev1980 commented
Final code review approved

2019-08-17 11:49 UTC, merged